<a href="https://colab.research.google.com/github/ApsanaMohammad/Machine_Learning_practice/blob/ml/2_NumPy_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style = "color:Red" >Working with NumPy</h1>


<h2 style = "color:Green"> Outcomes </h2>

#### At the end of this chapter, you will be able to
* Define NumPy data types
* Create and work with NumPy Arrays
* Understand the applications of NumpPy

<h2 style = "color:Green">What is Numpy?</h2>

* A Python package for scientific computations

* NumPy = ***Numerical Python***

* Numpy Library = Multi-dimensional array objects & Functions for processing it.

* Multi-dimensional object --> ___ndarray___ object

* Variaous operations supported: Arithmetic, Logical, Shape manipulation, Sort, DFT, Statistics, Random simulation etc.

* Importing NumPy: ___import numpy as np___

In [ ]:
# import numpy
import numpy as np

<h2 style = "color:Green"> Creating and Accessing ndarray object</h2>
    
* ndarray: Collection of items of the same type

    
* Items can be accessed using zero-based index.

    
* array() Function: ***numpy.array(object)***
                --> Creates an ndarray from an object.
                --> object: Any array or sequence.
               

<h3 style = "color:Blue">One Dimensional Array (Vector):</h3>

In [ ]:
# Create an one dimensional ndarray object from a list, display its values and type
l14=[1,2,3,4,5]
print(type(l14))
print(l14)

app1=np.array(l14)
print(type(app1))
print(app1)

<class 'list'>
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
# Create an one dimensional ndarray object from a tuple, display its values and type
tup1=(5,6,7,8,9,10)
print(type(tup1))
print(tup1)

app2=np.array(tup1)
print(type(app2))
print(app2)

<class 'tuple'>
(5, 6, 7, 8, 9, 10)
<class 'numpy.ndarray'>
[ 5  6  7  8  9 10]


In [ ]:
res1=range(11,16)

app3=np.array(res1)
print(type(app3))
print(app3)


<class 'numpy.ndarray'>
[11 12 13 14 15]


<h4 style = "color:Brown">Indexing & Slicing:</h4>

![oneDim.png](attachment:oneDim.png)

In [ ]:
# Create above one dimensional ndarray object and access its elements individually. And also slice some of its elements.
aap1=np.array([1,2,3,4,5])
print(aap1)

#indexing
print(aap1[0])
aap1[3]=aap1[3]+14
print(aap1)

[1 2 3 4 5]
1
[ 1  2  3 18  5]


<h3 style = "color:Blue">Two-Dimensional Arrays(Matrices)</h3>

* Each element  is itself 1D array


* arr2 = numpy.array([[row1], [row2], ...., [rowM]])


* Accessing an element: arr2[row_index, column_index]

In [ ]:
# Create a two dimensional array and access their rows and columns individually.
# Access the individual elements.
l2=[[1,1,1],[2,2,2],[3,3,3]]
print(l2)

a22=np.array(l2)
print(type(a22))
print(a22)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
<class 'numpy.ndarray'>
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
#Row  1
print(a22[0,:])
print(a22[0])

#column 2
print(a22[:,1])

#submatrix
print(a22[0:3,2:4])


[1 1 1]
[1 1 1]
[1 2 3]
[[1]
 [2]
 [3]]


<h2 style = "color:Green">ndarray Attribtes</h2>

* ndarray.ndim: Number of dimensions


* ndarry.shape: Array dimensions as a tuple.


* ndarry.size: Total number of elements


* ndarry.dtype: Type of the array elements.


* ndarray.itemsize: The size of each element in bytes

In [ ]:
# Create an one dimensional ndarray object and diplay all its attribute values.
print(app3)
print(app3.ndim)
print(app3.shape)
print(app3.size)
print(app3.dtype)
print(app3.itemsize)

[11 12 13 14 15]
1
(5,)
5
int64
8


In [ ]:
# Create a two dimensional ndarray object and diplay all its attribute values.
arr2=np.array([[4,4,4],[5,5,5]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)

[[4 4 4]
 [5 5 5]]
2
(2, 3)
6
int64
8


<h2 style = "color:Green">Other NumPy array creation functions</h2>

#### zeros(shape)
* Returns an array of zeros with specified shape
* Dafalut dtype is float



#### ones(shape)
* Returns an array of ones with specified shape
* Dafalut dtype is float


#### arange(start, stop, step, dtype)
* Returns an ndarray object with elements decided by start, stop and step arguments.
* Note that stop value is not including in the array.
* Default dtype is type is determined by type of start or stop values.

#### linspace(start, stop, N, dtype)
* Returns an ndarray object with N elements in the range from start value to stop stop .
* Note that stop value is inclusive in the array.
* Defaul type is float64

In [ ]:
# Create ndarray objects with all zeros using different dimensions and dtypes.

z=np.zeros(4)
print(z)


z1=np.zeros(4,dtype=np.int8)
print(z1)




[0. 0. 0. 0.]
[0 0 0 0]


In [ ]:
# Create ndarray objects with all ones using different dimensions and dtypes.
z2=np.ones(4)
print(z2)


z3=np.ones(4,dtype=np.int8)
print(z3)

[1. 1. 1. 1.]
[1 1 1 1]


In [ ]:
# Create one dimensional ndarray objects with various range of values and dtypes.
z4=np.arange(1,11,2)
print(z4)


z5=np.arange(1,11,2,dtype=np.int8)
print(z5)

[1 3 5 7 9]
[1 3 5 7 9]


In [ ]:
# Create one dimensional ndarray objects with 25 elements between 1 and 100 of different dtypes.
z6=np.linspace(1,100,25)
print(z6)

z7=np.linspace(1,100,25,dtype=np.int8)
print(z7)

[  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]
[  1   5   9  13  17  21  25  29  34  38  42  46  50  54  58  62  67  71
  75  79  83  87  91  95 100]


<h3 style = "color:green">Reshaping using reshape(shape) method</h3>

In [ ]:
# Reshape any of the above ndarray object using reshape method
z8=z7.reshape((5,-1))
print(z8)


[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
